# Calculate Well Trajectory from Different Data Sources

This notebook shows examples of how to calculate the well trajectory from different data sources.
Currently accepting data from CSV, dataframe, dictionary, and json.

The data from csv and dataframe must be in a certain format commonly seen in directional surveys.
The dictionary and json must be in a format specific to the library.

In [1]:
# ONLY RUN ONCE, must restart notebook otherwise
import pandas as pd
import os
from pathlib import Path
current_dir = Path.cwd()
path = current_dir.parent
print(path)
#change directory to get src class data
os.chdir(path)
#from src.data_object import *
#from src.calculable_object import *
from src.wellbore_trajectory import *
from src.data_source import *

C:\Users\BpAmos\Documents\repos\directional-survey-converter

## Get Wellbore Trajectory object

In [2]:
#json_path = path/'data/wellbore_survey.json'

In [3]:
file_paths = get_files(path, folders='data')
file_paths.items

[WindowsPath('C:/Users/BpAmos/Documents/repos/directional-survey-converter/data/wellbore_survey.csv'),
 WindowsPath('C:/Users/BpAmos/Documents/repos/directional-survey-converter/data/wellbore_survey.json'),
 WindowsPath('C:/Users/BpAmos/Documents/repos/directional-survey-converter/data/wellbore_survey_many.csv'),
 WindowsPath('C:/Users/BpAmos/Documents/repos/directional-survey-converter/data/well_C.csv'),
 WindowsPath('C:/Users/BpAmos/Documents/repos/directional-survey-converter/data/well_header.csv'),
 WindowsPath('C:/Users/BpAmos/Documents/repos/directional-survey-converter/data/well_interpolate_data.csv')]

In [4]:
# def calculate_wellbore_trajectory(path):
    
#     print(path)
    
#     # get wellbore trajectory object from json path
#     dev_obj = WellboreTrajectory.from_json(path)
#     # calculate survey points
#     dev_obj.calculate_survey_points()
#     # deserialize
#     json_ds = dev_obj.deserialize()
#     # load and convert to df
#     #json_ds_obj = json.loads(json_ds)
#     #df_min_curve = pd.DataFrame(json_ds_obj)
    
#     return json_ds
    

# json_path = get_files(path, folders='data', extensions='.json')
# #json_path.items
# calculate_wellbore_trajectory(json_path.items[0])

## From JSON

In [5]:
# json_path = get_files(path, folders='data', extensions='.json')
# json_path.items[0]


# my_data = DataSource.from_json(json_path.items[0])

# my_data.data

## From Dict

In [6]:
json_path = get_files(path, folders='data', extensions='.json')
json_path.items[0]

with open(json_path.items[0]) as json_file:
    json_data = json.load(json_file)
json_file.close()

my_data = DataSource.from_dictionary(json_data)

my_data.data
dev_obj = WellboreTrajectory(my_data.data)
dev_obj.deviation_survey_obj
dev_obj.calculate_survey_points()
json_ds = dev_obj.deserialize()
json_ds_obj = json.loads(json_ds)
df_min_curve = pd.DataFrame(json_ds_obj)
df_min_curve

,wellId,md,inc,azim,tvd,e_w_deviation,n_s_deviation,dls,surface_latitude,surface_longitude,longitude_points,latitude_points,zone_number,zone_letter,x_points,y_points,surface_x,surface_y,isHorizontal
0,well_C,0.00,0.00,227.11,0.000000,0.000000e+00,0.000000e+00,0.000000,29.908294,47.688521,47.688524,29.908294,38,R,759587.934440,3.311662e+06,759587.93444,3.311662e+06,Vertical
1,well_C,35.00,0.00,227.11,35.000000,-1.484001e-17,-1.378531e-17,0.000000,29.908294,47.688521,47.688524,29.908294,38,R,759587.934440,3.311662e+06,759587.93444,3.311662e+06,Vertical
2,well_C,774.81,0.46,227.11,774.802052,-2.175842e+00,-2.021203e+00,0.062178,29.908294,47.688521,47.688517,29.908289,38,R,759587.271243,3.311661e+06,759587.93444,3.311662e+06,Vertical
3,well_C,800.00,0.13,163.86,799.991684,-2.241984e+00,-2.117474e+00,1.312323,29.908294,47.688521,47.688516,29.908289,38,R,759587.251083,3.311661e+06,759587.93444,3.311662e+06,Vertical
4,well_C,900.00,0.57,230.43,899.989571,-2.593878e+00,-2.543311e+00,0.439221,29.908294,47.688521,47.688515,29.908288,38,R,759587.143826,3.311661e+06,759587.93444,3.311662e+06,Vertical
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105,well_C,10613.00,89.88,27.59,7660.358132,2.408116e+03,2.536985e+03,0.025961,29.908294,47.688521,47.696306,29.915110,38,R,760321.928281,3.312435e+06,759587.93444,3.311662e+06,Horizontal
106,well_C,10707.00,90.00,26.69,7660.456505,2.450995e+03,2.620632e+03,0.120140,29.908294,47.688521,47.696448,29.915337,38,R,760334.997584,3.312461e+06,759587.93444,3.311662e+06,Horizontal
107,well_C,10802.00,89.72,26.72,7660.688569,2.493687e+03,2.705499e+03,0.294745,29.908294,47.688521,47.696589,29.915568,38,R,760348.010275,3.312487e+06,759587.93444,3.311662e+06,Horizontal
108,well_C,10851.00,90.06,27.04,7660.782610,2.515841e+03,2.749204e+03,0.692054,29.908294,47.688521,47.696662,29.915686,38,R,760354.762783,3.312500e+06,759587.93444,3.311662e+06,Horizontal
109,well_C,10890.00,90.00,27.35,7660.762163,2.533665e+03,2.783893e+03,0.155997,29.908294,47.688521,47.696721,29.915780,38,R,760360.195456,3.312510e+06,759587.93444,3.311662e+06,Horizontal

## From DF

In [7]:
# FROM DF
csv_path = get_files(path, folders='data', extensions='.csv')
csv_path.items[0]

df = pd.read_csv(csv_path.items[0],sep=',')

my_data = DataSource.from_df(df, wellId_name='wellId',md_name='md',inc_name='inc',azim_name='azim',
         surface_latitude_name='surface_latitude',surface_longitude_name='surface_longitude')

my_data.data
dev_obj = WellboreTrajectory(my_data.data)
dev_obj.deviation_survey_obj
dev_obj.calculate_survey_points()
json_ds = dev_obj.deserialize()
json_ds_obj = json.loads(json_ds)
df_min_curve = pd.DataFrame(json_ds_obj)
df_min_curve

,wellId,md,inc,azim,tvd,e_w_deviation,n_s_deviation,dls,surface_latitude,surface_longitude,longitude_points,latitude_points,zone_number,zone_letter,x_points,y_points,surface_x,surface_y,isHorizontal
0,well_C,0.00,0.00,227.11,0.000000,0.000000e+00,0.000000e+00,0.000000,29.908294,47.688521,47.688524,29.908294,38,R,759587.934440,3.311662e+06,759587.93444,3.311662e+06,Vertical
1,well_C,35.00,0.00,227.11,35.000000,-1.484001e-17,-1.378531e-17,0.000000,29.908294,47.688521,47.688524,29.908294,38,R,759587.934440,3.311662e+06,759587.93444,3.311662e+06,Vertical
2,well_C,774.81,0.46,227.11,774.802052,-2.175842e+00,-2.021203e+00,0.062178,29.908294,47.688521,47.688517,29.908289,38,R,759587.271243,3.311661e+06,759587.93444,3.311662e+06,Vertical
3,well_C,800.00,0.13,163.86,799.991684,-2.241984e+00,-2.117474e+00,1.312323,29.908294,47.688521,47.688516,29.908289,38,R,759587.251083,3.311661e+06,759587.93444,3.311662e+06,Vertical
4,well_C,900.00,0.57,230.43,899.989571,-2.593878e+00,-2.543311e+00,0.439221,29.908294,47.688521,47.688515,29.908288,38,R,759587.143826,3.311661e+06,759587.93444,3.311662e+06,Vertical
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105,well_C,10613.00,89.88,27.59,7660.358132,2.408116e+03,2.536985e+03,0.025961,29.908294,47.688521,47.696306,29.915110,38,R,760321.928281,3.312435e+06,759587.93444,3.311662e+06,Horizontal
106,well_C,10707.00,90.00,26.69,7660.456505,2.450995e+03,2.620632e+03,0.120140,29.908294,47.688521,47.696448,29.915337,38,R,760334.997584,3.312461e+06,759587.93444,3.311662e+06,Horizontal
107,well_C,10802.00,89.72,26.72,7660.688569,2.493687e+03,2.705499e+03,0.294745,29.908294,47.688521,47.696589,29.915568,38,R,760348.010275,3.312487e+06,759587.93444,3.311662e+06,Horizontal
108,well_C,10851.00,90.06,27.04,7660.782610,2.515841e+03,2.749204e+03,0.692054,29.908294,47.688521,47.696662,29.915686,38,R,760354.762783,3.312500e+06,759587.93444,3.311662e+06,Horizontal
109,well_C,10890.00,90.00,27.35,7660.762163,2.533665e+03,2.783893e+03,0.155997,29.908294,47.688521,47.696721,29.915780,38,R,760360.195456,3.312510e+06,759587.93444,3.311662e+06,Horizontal

# From CSV

In [8]:
csv_path = get_files(path, folders='data', extensions='.csv')

my_data = DataSource.from_csv(csv_path.items[0], wellId_name='wellId',md_name='md',inc_name='inc',azim_name='azim',
         surface_latitude_name='surface_latitude',surface_longitude_name='surface_longitude')

my_data.data
dev_obj = WellboreTrajectory(my_data.data)
dev_obj.deviation_survey_obj
dev_obj.calculate_survey_points()
json_ds = dev_obj.deserialize()
json_ds_obj = json.loads(json_ds)
df_min_curve = pd.DataFrame(json_ds_obj)
df_min_curve

,wellId,md,inc,azim,tvd,e_w_deviation,n_s_deviation,dls,surface_latitude,surface_longitude,longitude_points,latitude_points,zone_number,zone_letter,x_points,y_points,surface_x,surface_y,isHorizontal
0,well_C,0.00,0.00,227.11,0.000000,0.000000e+00,0.000000e+00,0.000000,29.908294,47.688521,47.688524,29.908294,38,R,759587.934440,3.311662e+06,759587.93444,3.311662e+06,Vertical
1,well_C,35.00,0.00,227.11,35.000000,-1.484001e-17,-1.378531e-17,0.000000,29.908294,47.688521,47.688524,29.908294,38,R,759587.934440,3.311662e+06,759587.93444,3.311662e+06,Vertical
2,well_C,774.81,0.46,227.11,774.802052,-2.175842e+00,-2.021203e+00,0.062178,29.908294,47.688521,47.688517,29.908289,38,R,759587.271243,3.311661e+06,759587.93444,3.311662e+06,Vertical
3,well_C,800.00,0.13,163.86,799.991684,-2.241984e+00,-2.117474e+00,1.312323,29.908294,47.688521,47.688516,29.908289,38,R,759587.251083,3.311661e+06,759587.93444,3.311662e+06,Vertical
4,well_C,900.00,0.57,230.43,899.989571,-2.593878e+00,-2.543311e+00,0.439221,29.908294,47.688521,47.688515,29.908288,38,R,759587.143826,3.311661e+06,759587.93444,3.311662e+06,Vertical
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105,well_C,10613.00,89.88,27.59,7660.358132,2.408116e+03,2.536985e+03,0.025961,29.908294,47.688521,47.696306,29.915110,38,R,760321.928281,3.312435e+06,759587.93444,3.311662e+06,Horizontal
106,well_C,10707.00,90.00,26.69,7660.456505,2.450995e+03,2.620632e+03,0.120140,29.908294,47.688521,47.696448,29.915337,38,R,760334.997584,3.312461e+06,759587.93444,3.311662e+06,Horizontal
107,well_C,10802.00,89.72,26.72,7660.688569,2.493687e+03,2.705499e+03,0.294745,29.908294,47.688521,47.696589,29.915568,38,R,760348.010275,3.312487e+06,759587.93444,3.311662e+06,Horizontal
108,well_C,10851.00,90.06,27.04,7660.782610,2.515841e+03,2.749204e+03,0.692054,29.908294,47.688521,47.696662,29.915686,38,R,760354.762783,3.312500e+06,759587.93444,3.311662e+06,Horizontal
109,well_C,10890.00,90.00,27.35,7660.762163,2.533665e+03,2.783893e+03,0.155997,29.908294,47.688521,47.696721,29.915780,38,R,760360.195456,3.312510e+06,759587.93444,3.311662e+06,Horizontal

## From CSV with multiple wells

In [9]:
def from_multiple_wells_to_dict(df: DataFrame, wellId_name: Optional[str] = None, md_name: Optional[str] = None,
                                inc_name: Optional[str] = None, azim_name: Optional[str] = None,
                                surface_latitude_name: Optional[str] = None,
                                surface_longitude_name: Optional[str] = None,
                                surface_x_name: Optional[str] = None,
                                surface_y_name: Optional[str] = None):
    """
    takes a df of mulitple well deviation surveys in a typical columnar fashion and calculates their survey points.
    Then appends them to a list of dicts.

    :parameter: df

    :returns: list of dict
    """
    # group by wellId, ensures this will work with single well or mulitple.
    grouped = df.groupby(wellId_name)

    # initialize empty dict and list
    #appended_df = pd.DataFrame()
    dict_list = []
    # loop through groups converting them to the proper dict format
    for name, group in grouped:

        group.reset_index(inplace=True, drop=True)

        if surface_latitude_name is not None and surface_longitude_name is not None:
            well_obj = DataSource.from_df(group, wellId_name=wellId_name, md_name=md_name,
                                          inc_name=inc_name, azim_name=azim_name,
                                          surface_latitude_name=surface_latitude_name,
                                          surface_longitude_name=surface_longitude_name)

        if surface_x_name is not None and surface_y_name is not None:
            well_obj = DataSource.from_df(group, wellId_name=wellId_name, md_name=md_name,
                                          inc_name=inc_name, azim_name=azim_name,
                                          surface_x_name=surface_x_name,
                                          surface_y_name=surface_y_name)

        well_obj = WellboreTrajectory(well_obj.data)
        well_obj.calculate_survey_points()
        json_ds = well_obj.deserialize()
        # dict_list.append(json_ds)
        # TODO: should it be a list of serialized or deserialized dicts
        # json_ds_obj = json.loads(json_ds)
        dict_list.append(json_ds)
        # df_well_obj = pd.DataFrame(json_ds_obj)
        # appended_df = appended_df.append(df_well_obj)
    res = dict_list
    # res = appended_df
    return res

In [14]:
# FROM df with mulitple wells
csv_path = get_files(path, folders='data', extensions='.csv')
csv_path.items[1]

df = pd.read_csv(csv_path.items[1])
df

dicts = from_multiple_wells_to_dict(df,wellId_name='wellId',md_name='md',inc_name='inc',azim_name='azim',
                                     surface_latitude_name='surface_latitude',surface_longitude_name='surface_longitude')
#dicts[:]

In [22]:
def list_of_dicts_to_df(dict_list):
    """takes a list of dicts and converts to a appended df"""
    appended_df = pd.DataFrame()
    for i in dict_list:
        json_ds_obj = json.loads(i)
        df_well_obj = pd.DataFrame(json_ds_obj)
        appended_df = appended_df.append(df_well_obj)
    return appended_df

In [23]:
df = list_of_dicts_to_df(dicts)
df

,wellId,md,inc,azim,tvd,e_w_deviation,n_s_deviation,dls,surface_latitude,surface_longitude,longitude_points,latitude_points,zone_number,zone_letter,x_points,y_points,surface_x,surface_y,isHorizontal
0,well_A,0.0000,0.00,227.11,0.000000,0.000000e+00,0.000000e+00,0.000000,29.908294,47.688521,47.688524,29.908294,38,R,759587.932586,3.311662e+06,759587.932586,3.311662e+06,Vertical
1,well_A,36.7500,0.00,227.11,36.750000,-1.558201e-17,-1.447458e-17,0.000000,29.908294,47.688521,47.688524,29.908294,38,R,759587.932586,3.311662e+06,759587.932586,3.311662e+06,Vertical
2,well_A,813.5505,0.46,227.11,813.542155,-2.284634e+00,-2.122263e+00,0.059217,29.908294,47.688521,47.688516,29.908289,38,R,759587.236230,3.311661e+06,759587.932586,3.311662e+06,Vertical
3,well_A,840.0000,0.13,163.86,839.991268,-2.354083e+00,-2.223348e+00,1.249832,29.908294,47.688521,47.688516,29.908288,38,R,759587.215062,3.311661e+06,759587.932586,3.311662e+06,Vertical
4,well_A,945.0000,0.57,230.43,944.989049,-2.723571e+00,-2.670477e+00,0.418306,29.908294,47.688521,47.688515,29.908287,38,R,759587.102442,3.311661e+06,759587.932586,3.311662e+06,Vertical
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105,well_C,10613.0000,89.88,27.59,7660.358132,2.408116e+03,2.536985e+03,0.025961,29.908294,47.688521,47.696306,29.915110,38,R,760321.928281,3.312435e+06,759587.934440,3.311662e+06,Horizontal
106,well_C,10707.0000,90.00,26.69,7660.456505,2.450995e+03,2.620632e+03,0.120140,29.908294,47.688521,47.696448,29.915337,38,R,760334.997584,3.312461e+06,759587.934440,3.311662e+06,Horizontal
107,well_C,10802.0000,89.72,26.72,7660.688569,2.493687e+03,2.705499e+03,0.294745,29.908294,47.688521,47.696589,29.915568,38,R,760348.010275,3.312487e+06,759587.934440,3.311662e+06,Horizontal
108,well_C,10851.0000,90.06,27.04,7660.782610,2.515841e+03,2.749204e+03,0.692054,29.908294,47.688521,47.696662,29.915686,38,R,760354.762783,3.312500e+06,759587.934440,3.311662e+06,Horizontal
109,well_C,10890.0000,90.00,27.35,7660.762163,2.533665e+03,2.783893e+03,0.155997,29.908294,47.688521,47.696721,29.915780,38,R,760360.195456,3.312510e+06,759587.934440,3.311662e+06,Horizontal